# Generated by Django 4.2.7 on 2024-03-10 13:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0002_apikey'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='key',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
